/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *                         
 * @author SP
 */
public class ProyectoMatrices3 extends javax.swing.JFrame {

    /**
     * Creates new form ProyectoMatrices3
     */
    public ProyectoMatrices3() {
        initComponents();

        JButton botonesHabilitar[] = {cmdCrear, cmdBorrar};
        JButton botonesDesabilitar[] = {cmdManual, cmdAuto, cmdRecorrido};

        Helper.habilitarBotones(botonesHabilitar);
        Helper.deshabilitarBotones(botonesDesabilitar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFilas = new javax.swing.JTextField();
        txtColumnas = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdManual = new javax.swing.JButton();
        cmdAuto = new javax.swing.JButton();
        cmdRecorrido = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaInicial = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtLineal = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtLetras = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtCaracol = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cmbLineal = new javax.swing.JComboBox();
        cmbLetras = new javax.swing.JComboBox();
        cmbCaracol = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arabic Typesetting", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Proyecto Matrices");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 150, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 2, 14), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tunga", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 204, 0));
        jLabel2.setText("Filas");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, -1));

        jLabel3.setFont(new java.awt.Font("Tunga", 2, 18)); // NOI18N
        jLabel3.setText("Columnas");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, -1));

        txtFilas.setFont(new java.awt.Font("Tunga", 2, 18)); // NOI18N
        txtFilas.setForeground(new java.awt.Color(204, 102, 255));
        txtFilas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFilasKeyTyped(evt);
            }
        });
        jPanel2.add(txtFilas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 70, 30));

        txtColumnas.setFont(new java.awt.Font("Tunga", 2, 18)); // NOI18N
        txtColumnas.setForeground(new java.awt.Color(0, 153, 204));
        txtColumnas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtColumnasKeyTyped(evt);
            }
        });
        jPanel2.add(txtColumnas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 70, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 190, 110));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Galeria De Botones\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 2, 14), new java.awt.Color(102, 0, 102))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        cmdCrear.setForeground(new java.awt.Color(255, 153, 0));
        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel3.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        cmdManual.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        cmdManual.setForeground(new java.awt.Color(255, 0, 153));
        cmdManual.setText("Manual");
        cmdManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdManualActionPerformed(evt);
            }
        });
        jPanel3.add(cmdManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        cmdAuto.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        cmdAuto.setForeground(new java.awt.Color(0, 204, 204));
        cmdAuto.setText("Auto");
        cmdAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAutoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdAuto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, -1));

        cmdRecorrido.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        cmdRecorrido.setForeground(new java.awt.Color(255, 255, 0));
        cmdRecorrido.setText("Recorrido");
        cmdRecorrido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRecorridoActionPerformed(evt);
            }
        });
        jPanel3.add(cmdRecorrido, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 160, -1));

        cmdSalir.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel3.add(cmdSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 80, -1));

        cmdBorrar.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        cmdBorrar.setForeground(new java.awt.Color(255, 0, 0));
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 160, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 190, 190));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 2, 14), new java.awt.Color(204, 0, 51))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblTablaInicial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblTablaInicial.setEnabled(false);
        jScrollPane1.setViewportView(tblTablaInicial);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 20, 470, 200));

        txtLineal.setEditable(false);
        txtLineal.setColumns(20);
        txtLineal.setFont(new java.awt.Font("MS Mincho", 2, 18)); // NOI18N
        txtLineal.setForeground(new java.awt.Color(255, 153, 0));
        txtLineal.setRows(5);
        jScrollPane2.setViewportView(txtLineal);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 470, 60));

        jLabel5.setFont(new java.awt.Font("Tunga", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 102, 0));
        jLabel5.setText("Lineal");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 50, -1));

        txtLetras.setEditable(false);
        txtLetras.setColumns(20);
        txtLetras.setFont(new java.awt.Font("MS Mincho", 2, 18)); // NOI18N
        txtLetras.setForeground(new java.awt.Color(0, 51, 204));
        txtLetras.setRows(5);
        jScrollPane3.setViewportView(txtLetras);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 470, 60));

        jLabel6.setFont(new java.awt.Font("Tunga", 2, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 204, 0));
        jLabel6.setText("Letras");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 50, -1));

        txtCaracol.setEditable(false);
        txtCaracol.setColumns(20);
        txtCaracol.setFont(new java.awt.Font("MS Mincho", 2, 18)); // NOI18N
        txtCaracol.setForeground(new java.awt.Color(204, 0, 255));
        txtCaracol.setRows(5);
        jScrollPane4.setViewportView(txtCaracol);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 470, 60));

        jLabel7.setFont(new java.awt.Font("Tunga", 2, 18)); // NOI18N
        jLabel7.setText("Caracol");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 60, 20));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 490, 490));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Combos Recorridos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tunga", 0, 14), new java.awt.Color(0, 0, 153))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbLineal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Recorrido Lineal Uno ", "Recorrido Lineal Dos" }));
        jPanel5.add(cmbLineal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 150, -1));

        cmbLetras.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Recorrido Letra Z ", "Recorrido Letra M" }));
        jPanel5.add(cmbLetras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 150, -1));

        cmbCaracol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laberinto De Caracol" }));
        jPanel5.add(cmbCaracol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 150, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 190, 130));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/playstation_wallpaper___2015_by_jnsvmli_by_jnsvmli-d8e2okf.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(736, 566));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        txtFilas.setText("");
        txtColumnas.setText("");
        txtLineal.setText("");
        txtFilas.requestFocusInWindow();
        cmbLineal.setSelectedIndex(0);
        cmbLetras.setSelectedIndex(0); 
        cmbCaracol.setSelectedIndex(0);
        txtLetras.setText(""); 
        txtCaracol.setText("");

        Helper.porDefectoTabla(tblTablaInicial);

        JButton botonesHabilitar[] = {cmdCrear, cmdBorrar};
        JButton botonesDesabilitar[] = {cmdManual, cmdAuto, cmdRecorrido};

        Helper.habilitarBotones(botonesHabilitar);
        Helper.deshabilitarBotones(botonesDesabilitar);
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int numfilas, numcolumnas;

        DefaultTableModel tm;

        if (txtFilas.getText().trim().isEmpty()) {
            Helper.recorrido(this, "Ingrese filas", 1);
            txtFilas.requestFocusInWindow();
        } else if (txtColumnas.getText().trim().isEmpty()) {
            Helper.recorrido(this, "Ingrese Columnas", 1);
            txtColumnas.requestFocusInWindow();
        } else {
            numfilas = Integer.parseInt(txtFilas.getText());
            numcolumnas = Integer.parseInt(txtColumnas.getText());

            if (numfilas != numcolumnas) {
                Helper.recorrido(this, "Las filas y columnas para crear la matriz deben ser iguales", 3);
                txtFilas.requestFocusInWindow();
                txtColumnas.requestFocusInWindow();
            } else if (numfilas == 0) {
                Helper.recorrido(this, "Las filas no pueden ser cero", 1);
                txtFilas.requestFocusInWindow();
            } else if (numcolumnas == 0) {
                Helper.recorrido(this, "Las columnas no pueden ser cero", 1);
                txtColumnas.requestFocusInWindow();
            } else if (numfilas == 1 || numfilas == 3) {
                Helper.recorrido(this, "Las filas no pueden ser uno ni tres", 1);
                txtFilas.requestFocusInWindow();
            } else if (numcolumnas == 1 || numfilas == 3) {
                Helper.recorrido(this, "Las columnas no pueden ser uno ni tres", 1);
                txtColumnas.requestFocusInWindow();
            } else if (numfilas >= 15) {
                Helper.recorrido(this, "Los valores a ingresar en la tabla no pueden ser igual o mayor a 15", 2);
                txtFilas.requestFocusInWindow();
            } else if (numcolumnas >= 15) {
                Helper.recorrido(this, "Los valores a ingresar en la tabla no pueden ser igual o mayor a 15", 2);
                txtColumnas.requestFocusInWindow();
            } else if (numfilas % 2 == 0) {
                Helper.recorrido(this, "Las filas deben ser impares", 1);
                txtFilas.requestFocusInWindow();
            } else if (numcolumnas % 2 == 0) {
                Helper.recorrido(this, "Las columnas deben ser impares", 1);
                txtColumnas.requestFocusInWindow();

            } else {
                tm = (DefaultTableModel) tblTablaInicial.getModel();

                tm.setRowCount(numfilas);
                tm.setColumnCount(numcolumnas);

                JButton botonesHabilitar[] = {cmdManual, cmdAuto, cmdBorrar};
                JButton botonesDesabilitar[] = {cmdCrear, cmdRecorrido};

                Helper.habilitarBotones(botonesHabilitar);
                Helper.deshabilitarBotones(botonesDesabilitar);
            }

        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdManualActionPerformed
        int numfilas, numcolumnas;
        int n;
        int sw, res;

        numcolumnas = tblTablaInicial.getColumnCount();
        numfilas = tblTablaInicial.getRowCount();

        for (int i = 0; i < numfilas; i++) {
            for (int j = 0; j < numcolumnas; j++) {
                do {
                    sw = 1;
                    try {
                        n = Integer.parseInt(JOptionPane.showInputDialog(this, "Digite el elmento en la posición [" + i + "]" + "[" + j + "]").trim());
                        tblTablaInicial.setValueAt(n, i, j);
                    } catch (NumberFormatException e) {
                        Helper.recorrido(this, "Digite un número válido", 1);
                        sw = 0;
                    } catch (NullPointerException e) {
                        res = JOptionPane.showConfirmDialog(this, "¿Seguro que desea salir?", "Salir", JOptionPane.YES_NO_OPTION);
                        if (res == 0) {
                            sw = 1;
                            i = numfilas;
                            j = numcolumnas;

                            Helper.porDefectoTabla(tblTablaInicial);

                        } else {
                            sw = 0;
                        }
                    }
                } while (sw == 0);
            }
        }
        JButton botonesH[] = {cmdRecorrido, cmdBorrar};
        JButton botonesD[] = {cmdCrear, cmdManual, cmdAuto};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdManualActionPerformed

    private void cmdAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAutoActionPerformed
        int numfilas, numcolumnas, n;
        numcolumnas = tblTablaInicial.getColumnCount();
        numfilas = tblTablaInicial.getRowCount();

        for (int i = 0; i < numfilas; i++) {
            for (int j = 0; j < numcolumnas; j++) {
                n = (int) (Math.random() * 50 + 1);
                tblTablaInicial.setValueAt(n, i, j);
            }
        }
        JButton botonesH[] = {cmdRecorrido, cmdBorrar};
        JButton botonesD[] = {cmdCrear, cmdManual, cmdAuto};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdAutoActionPerformed

    private void cmdRecorridoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRecorridoActionPerformed
        int lineal = cmbLineal.getSelectedIndex();
        int letras = cmbLetras.getSelectedIndex();
        int caracol = cmbCaracol.getSelectedIndex();          

        switch (lineal) {
            case 0:
                txtLineal.setText(Helper.recorridoLinealUno(tblTablaInicial));
                break;
            case 1:
                txtLineal.setText(Helper.recorridoLinealDos(tblTablaInicial));
                break;
        }
        switch (letras) {
            case 0:
                txtLetras.setText(Helper.recorridoLetraZ(tblTablaInicial));
                break;
            case 1:
                txtLetras.setText(Helper.recorridoLetraM(tblTablaInicial));
                break;
        }
        switch (caracol) {
            case 0:
                txtCaracol.setText(Helper.laberintoDeCaracol(tblTablaInicial));
                break;
        }
        JButton botonesHabilitar[] = {cmdRecorrido, cmdBorrar};
        JButton botonesDesabilitar[] = {cmdManual, cmdAuto};

        Helper.habilitarBotones(botonesHabilitar);
        Helper.deshabilitarBotones(botonesDesabilitar);
    }//GEN-LAST:event_cmdRecorridoActionPerformed

    private void txtFilasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFilasKeyTyped
       char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isSpaceChar(c) || !Character.isDigit(c)) {
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_txtFilasKeyTyped

    private void txtColumnasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtColumnasKeyTyped
      char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isSpaceChar(c) || !Character.isDigit(c)) {
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_txtColumnasKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProyectoMatrices3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProyectoMatrices3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProyectoMatrices3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProyectoMatrices3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProyectoMatrices3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCaracol;
    private javax.swing.JComboBox cmbLetras;
    private javax.swing.JComboBox cmbLineal;
    private javax.swing.JButton cmdAuto;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdManual;
    private javax.swing.JButton cmdRecorrido;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblTablaInicial;
    private javax.swing.JTextArea txtCaracol;
    private javax.swing.JTextField txtColumnas;
    private javax.swing.JTextField txtFilas;
    private javax.swing.JTextArea txtLetras;
    private javax.swing.JTextArea txtLineal;
    // End of variables declaration//GEN-END:variables
}
